name: CI/CD Scan by AccuKnox
description: 'Secure your CI/CD pipelines, powered by KubeArmor'
branding:
  icon: shield
  color: green
author: AccuKnox

inputs:
  all:
    description: 'Scan for all events collected by KubeArmor'
    required: false
    default: 'true'
  system:
    description: 'Scan for only system events'
    required: false
    default: 'false'
  output:
    description: 'Output path for the files to be placed'
    required: false
    default: './knoxctl-results'
  kubearmor_version:
    description: 'KubeArmor version to install (default: latest)'
    required: false
  knoxctl_version:
    description: 'knoxctl version to install (default: latest)'
    required: false
  policy_action:
    description: 'Policy action (Audit or Block)'
    required: false
    default: 'Audit'

runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
