name: CI/CD Scan by AccuKnox
description: 'Secure your CI/CD pipelines, powered by KubeArmor'
branding:
  icon: shield
  color: green
author: AccuKnox

inputs:
  all:
    description: 'Scan for all events collected by KubeArmor'
    required: false
    default: 'true'
  system:
    description: 'Scan for only system events'
    required: false
    default: 'false'
  kubearmor_version:
    description: 'KubeArmor version to install (default: latest)'
    required: false
  knoxctl_version:
    description: 'knoxctl version to install (default: latest)'
    required: false
  policy_action:
    description: 'Policy action (Audit or Block)'
    required: false
    default: 'Audit'
  dryrun:
    description: 'Generate hardening security policies, but do not apply them'
    required: false
    default: 'false'
  strict:
    description: 'Apply all the hardening policies (this might generate a lot of alerts)'
    required: false
    default: 'false'
  policies:
    description: 'Path to user defined policies'
    required: false
  ignore-alerts:
    description: 'Ignore alerts (file, network or process)'
    required: false
  min-severity:
    description: 'Set the minimum severity level (1-10)'
    required: false
  detailed-view:
    description: 'Enable/disable detailed view in final report'
    required: false
    default: 'true'


runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
