name: accuknox-report
description: 'Generate reports using kubearmor and discovery engine'
inputs:
  baseline:
    description: 'baseline report path'
    required: true
    default: "baseline/report.json"
  namespaces:
    description: 'namespaces. include specific namespaces for final report generation'
    required: false
    default: ""
  destination:
    description: 'destination. include specific destination paths for final report generation'
    required: false
    default: ""
  ignore-command:
    description: 'ignore-command. ignore network commands that should not be considered for final report generation'
    required: false
    default: ""
  ignore-path:
    description: 'ignore-path. ignore paths (source or destination) that should not be treated for final report generation'
    required: false
    default: ""
  workloads:
    description: 'workloads. filter the specific workloads format: <namespace>/<resource>'
    required: false
    default: ""
  source:
    description: 'source. include specific source paths for final report generation'
    required: false
    default: ""
  operation:
    description: 'operation. filter out by specific operation type such as file, process, network for final repot generation'
    required: false
    default: ""
  view:
    description: 'view type. possible value: table'
    required: false
    default: "table"

runs:
  using: "composite"
  steps:
    - name: Generate report
      run: |
        knoxctl --help

        setupArgs=""
        if [ "${{ inputs.baseline }}" != "" ]; then
          setupArgs+=" --baseline ${{ inputs.baseline }}"
        fi
        if [ "${{ inputs.operation }}" != "" ]; then 
          setupArgs+=" --operation ${{ inputs.operation }}"
        fi
        if [ "${{ inputs.workloads }}" != "" ]; then 
          setupArgs+=" --workload ${{ inputs.workloads }}"
        fi
        if [ "${{ inputs.namespaces }}" != "" ]; then 
          setupArgs+=" --namespaces ${{ inputs.namespaces }}"
        fi
        if [ "${{ inputs.source }}" != "" ]; then 
          setupArgs+=" --source ${{ inputs.source }}"
        fi
        if [ "${{ inputs.ignore-path }}" != "" ]; then 
          setupArgs+=" --ignore-path ${{ inputs.ignore-path }}"
        fi
        if [ "${{ inputs.ignore-command }}" != "" ]; then 
          setupArgs+=" --ignore-command ${{ inputs.ignore-command }}"
        fi
        if [ "${{ inputs.destination }}" != "" ]; then 
          setupArgs+=" --destination ${{ inputs.destination }}"
        fi
        if [ "${{ inputs.view }}" != "" ]; then
          setupArgs+=" --view ${{ inputs.view }}"
        fi
        
        sleep 360
        knoxctl report $setupArgs
        
        mkdir downloads
        mv /knoxctl_out/reports/latest_summary_*.json downloads/latest_summary.json
        mv /knoxctl_out/reports/diff_*.json downloads/diff.json
        mv /knoxctl_out/reports/pr_report_*.md downloads/pr_report.md
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Baseline report
        path: downloads
    
    - name: PR comment with file
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: downloads/diff-report.md

    - name: Generate Icon Badge
      uses: damienaicheh/icon-badge-action@v1.0.0
      with:
        images-path: './ak_logo.png'

